(use-modules (thales solver))
(define installed '())
(define available '((foo  (1 0 0)  ())
		    (foo  (2 0 0)  ())
		    (bar  (1 0 0)  ((foo ? (1 0 0))))
		    (bar  (2 0 0)  ((foo ? (2 0 0))))
		    (quad (1 0 0)  ((foo ? (1 0 0))
				    (bar ? (1 0 0))))
		    (quad (2 0 0)  ((foo ? (1 0 0))
				    (bar ? (2 0 0))))))

(define constrains '((quad ? (1 0) (2 0))))
(define r1-solver (generate-r1-contrain-solver installed available))
(define optimize-pkglist (@@ (thales solver) optimize-pkglist))
;; (display (resolve-major-versions r1-solver
;; 				 (list '(quad ? (1 0)))
;; 				 '()))
