#!/usr/bin/guile -s
!#
(use-modules (im irc))

(let ((session (create-connection
                 #:server "irc.freenode.net"
                 #:nickname "__GNU_THALES")))
  (add-hook! (hook-ref! session #:connect) (lambda (obj) (write obj) (join! obj "#thales-test")))
  (add-hook! (hook-ref! session #:notice) (lambda (obj source text) (write text)))
  (add-hook! (hook-ref! session #:channel) (lambda (obj channel source text)
               (display (format "~a:: ~a\n" source text))))
  (add-hook! (hook-ref! session #:privmsg) (lambda (obj source text) (write text)))
  (run! session))
